from __future__ import annotations

import re
from typing import Any


_LENGTH_RANGE_RE = re.compile(r"(\d{2,5})\s*(?:到|至|[-—~～])\s*(\d{2,5})\s*(?:个)?字")
_LENGTH_MAX_RE = re.compile(r"(?:不超过|至多|控制在)\s*(\d{2,5})\s*(?:个)?字")
_MARKDOWN_BULLET_RE = re.compile(r"(?m)^\s*[-*+]\s+")
_REQUIRED_TOPICS_RE = re.compile(r"(?:重点|主要)(?:包括|涵盖|围绕|写明|说明)\s*([^。；\n]+)")
_TOPIC_SPLIT_RE = re.compile(r"[、,，;；]|以及|和|与")
_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
_BODY_H2_RE = re.compile(r"^一、")
_BODY_H3_RE = re.compile(r"^（[一二三四五六七八九十百]+）")
_BODY_H4_RE = re.compile(r"^(?:\d+|[一二三四五六七八九十百]+)[.、]\s*")


def _issue(code: str, message: str, severity: str = "warning", suggestion: str = "") -> dict[str, Any]:
    return {
        "code": code,
        "severity": severity,
        "message": message,
        "suggestion": suggestion,
        "source": "document_linter",
    }


def normalize_markdown_headings(article: str) -> tuple[str, list[dict[str, Any]]]:
    """Normalize obvious public-document headings without rewriting body prose.

    Markdown H1 is reserved for the document title.  Later H1 lines generated by
    a model are demoted only when their text clearly follows the Chinese public
    document numbering convention; ambiguous numbered paragraphs are preserved.
    """
    lines = (article or "").replace("\r\n", "\n").replace("\r", "\n").split("\n")
    title_seen = False
    warnings: list[dict[str, Any]] = []
    normalized: list[str] = []
    for index, line in enumerate(lines):
        match = _HEADING_RE.match(line)
        if not match:
            normalized.append(line)
            continue
        hashes, text = match.groups()
        level = len(hashes)
        if level == 1 and not title_seen:
            title_seen = True
            normalized.append(f"# {text}")
            continue
        if level == 1:
            if _BODY_H2_RE.match(text):
                normalized.append(f"## {text}")
            elif _BODY_H3_RE.match(text):
                normalized.append(f"### {text}")
            elif _BODY_H4_RE.match(text):
                normalized.append(f"#### {text}")
            else:
                normalized.append(line)
                warnings.append(_issue(
                    "ambiguous_extra_title",
                    f"第 {index + 1} 行存在无法判断用途的额外一级标题",
                    "warning",
                    "请确认该行是文章题目还是正文标题",
                ))
            continue
        normalized.append(f"{'#' * level} {text}")
    return "\n".join(normalized).strip(), warnings


def lint_document(document_type: str, requirements: str, article: str) -> list[dict[str, Any]]:
    issues: list[dict[str, Any]] = []
    stripped = (article or "").strip()
    if not stripped:
        return [_issue("empty_article", "正文为空", "error", "重新生成完整正文")]
    heading_lines = [
        (index, match.groups())
        for index, line in enumerate(stripped.splitlines(), 1)
        if (match := _HEADING_RE.match(line))
    ]
    h1_lines = [(index, groups[1]) for index, groups in heading_lines if len(groups[0]) == 1]
    if not stripped.startswith("# "):
        issues.append(_issue("missing_title", "正文缺少一级标题", "error", "使用一个 Markdown 一级标题"))
    if len(h1_lines) > 1:
        issues.append(_issue(
            "multiple_document_titles",
            f"正文包含 {len(h1_lines)} 个 Markdown 一级标题，正文标题应使用二级及以下层级",
            "error",
            "仅保留文章题目为一级标题",
        ))
    if heading_lines:
        first_level = len(heading_lines[0][1][0])
        if first_level != 1:
            issues.append(_issue("title_not_first_heading", "文章题目不是第一个标题", "error"))
        previous = 1
        for index, groups in heading_lines[1:]:
            level = len(groups[0])
            if level > previous + 1:
                issues.append(_issue(
                    "heading_level_jump",
                    f"第 {index} 行标题从 H{previous} 跳到 H{level}",
                    "warning",
                    "按文章实际层级调整标题",
                ))
            previous = level
    if "---ARTICLE---" in stripped or "---SUMMARY---" in stripped:
        issues.append(_issue("legacy_marker", "正文包含旧输出协议标记", "error", "删除协议标记"))
    if _MARKDOWN_BULLET_RE.search(stripped):
        issues.append(
            _issue("markdown_bullets", "正文使用了 Markdown 项目符号", "warning", "改用正式公文编号")
        )

    length_match = _LENGTH_RANGE_RE.search(requirements or "")
    if length_match:
        minimum, maximum = map(int, length_match.groups())
        if len(stripped) < minimum * 0.8 or len(stripped) > maximum * 1.2:
            issues.append(_issue("length_range", f"正文长度与要求的 {minimum}—{maximum} 字偏差较大"))
    else:
        max_match = _LENGTH_MAX_RE.search(requirements or "")
        if max_match and len(stripped) > int(max_match.group(1)) * 1.2:
            issues.append(_issue("length_max", "正文明显超过用户限定字数"))

    required_topics = []
    for match in _REQUIRED_TOPICS_RE.finditer(requirements or ""):
        for topic in _TOPIC_SPLIT_RE.split(match.group(1)):
            normalized = topic.strip(" ：:。；;，,")
            if not normalized or normalized.startswith(("避免", "不得", "不要", "不写", "排除")):
                continue
            if 2 <= len(normalized) <= 30 and normalized not in required_topics:
                required_topics.append(normalized)
    missing_topics = [topic for topic in required_topics if topic not in stripped]
    if missing_topics:
        issues.append(_issue(
            "missing_required_topics",
            f"正文未覆盖用户明确列出的重点：{'、'.join(missing_topics)}",
            "error",
            "补充缺失重点，不得用无关内容代替",
        ))

    # Structure is selected by the writing plan and Skill.  The deterministic
    # layer only checks a numbering system after the draft has chosen to use it;
    # it must not force every notice into numbered sections or every short rule
    # into chapters and articles.
    if document_type == "regulation":
        has_articles = bool(re.search(r"第[一二三四五六七八九十百]+条", stripped))
        if has_articles and "第一条" not in stripped:
            issues.append(_issue(
                "article_numbering_start",
                "制度使用了条款编号但未从第一条开始",
                "error",
                "核对并连续编排已有条款，不新增空条款",
            ))
        has_chapters = bool(re.search(r"第[一二三四五六七八九十百]+章", stripped))
        if has_chapters and "第一章" not in stripped:
            issues.append(_issue(
                "chapter_numbering_start",
                "制度使用了章节编号但未从第一章开始",
                "error",
                "核对并连续编排已有章节，不新增空章节",
            ))

    return issues


def needs_revision(issues: list[dict[str, Any]]) -> bool:
    return any(issue.get("severity") == "error" for issue in issues)
